Models/ProjectDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BaiLam.Models
{
    public class ProjectDetail
    {
        public ProjectDetail()
        {

        }
        [Key]
        public int detailID { get; set; }
        [Required]
        [ForeignKey("Project")]
        public int ProjectID { get; set; }
        [Required]
        [ForeignKey("Employee")]
        public int EmployeeID { get; set; }
        [Column(TypeName ="nvarchar(100)")]
        public string Description { get; set; }
        public double Mon { get; set; }
        public double Tue { get; set; }
        public double Wed { get; set; }
        public double Thur { get; set; }
        public double Fri { get; set; }
        public double HoursWorked { get; set; }

        public virtual Project project { get; set; }
        public virtual Employee employee { get; set; }
    }
}

Controllers/ProjectDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaiLam.Models;
using Microsoft.AspNetCore.Authorization;
using ClosedXML.Excel;
using System.IO;

namespace BaiLam.Controllers
{
    [Authorize]
    public class ProjectDetailsController : Controller
    {
        private readonly TimeSheetContext _context;

        public ProjectDetailsController(TimeSheetContext context)
        {
            _context = context;
        }

        // GET: ProjectDetails
        public async Task<IActionResult> Index(int? id)
        {

            if (id == null) { return NotFound(); }
            ViewBag.ProID = id;
            var timeSheetContext = _context.ProjectDetails.Where(m => m.ProjectID == id).Include(p => p.employee).Include(p => p.project).Include(e => e.employee.role).Where(m => m.ProjectID == id);
            return View(await timeSheetContext.ToListAsync());
        }

        // GET: ProjectDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Url = _context.ProjectDetails.Where(p=>p.detailID==id).Include(m=>m.project).FirstOrDefault().ProjectID;
            var projectDetail = await _context.ProjectDetails
                .Include(p => p.employee)
                .Include(p => p.project)
                .FirstOrDefaultAsync(m => m.detailID == id);
            if (projectDetail == null)
            {
                return NotFound();
            }

            return View(projectDetail);
        }

        // GET: ProjectDetails/Create
        public IActionResult Create(int? id)
        {
            if (id == null) { return NotFound(); }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name");
            ViewData["ProjectID"] = new SelectList(_context.Projects.Where(p => p.ProjectID == id), "ProjectID", "ProjectName");
            return View();
        }

        // POST: ProjectDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("detailID,ProjectID,EmployeeID,Name,Description,Mon,Tue,Wed,Thur,Fri,HoursWorked")] ProjectDetail projectDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectDetail);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { id = projectDetail.ProjectID });
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // GET: ProjectDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectDetail = await _context.ProjectDetails.FindAsync(id);
            if (projectDetail == null)
            {
                return NotFound();
            }
            ViewBag.EmployeeName = _context.ProjectDetails.Where(p => p.detailID == id).Include(e=>e.employee).FirstOrDefault().employee.Name;
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // POST: ProjectDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("detailID,ProjectID,EmployeeID,Name,Description,Mon,Tue,Wed,Thur,Fri,HoursWorked")] ProjectDetail projectDetail)
        {
            if (id != projectDetail.detailID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectDetailExists(projectDetail.detailID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index),new { id=projectDetail.ProjectID});
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // GET: ProjectDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            var projectDetail = await _context.ProjectDetails
                .Include(p => p.employee)
                .Include(p => p.project)
                .FirstOrDefaultAsync(m => m.detailID == id);
            if (projectDetail == null)
            {
                return NotFound();
            }

            return View(projectDetail);
        }

        // POST: ProjectDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectDetail = await _context.ProjectDetails.FindAsync(id);
            _context.ProjectDetails.Remove(projectDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = projectDetail.ProjectID });
        }

        private bool ProjectDetailExists(int id)
        {
            return _context.ProjectDetails.Any(e => e.detailID == id);
        }

        public IActionResult Excel(int? id)
        {
            if (id == null) { return NotFound(); }
            var Employee = _context.ProjectDetails.Where(p => p.detailID == id).Include(e=>e.employee).Include(r=>r.employee.role).Include(b=>b.project).FirstOrDefault();

            using (var workbook = new XLWorkbook())
            {

                var worksheet = workbook.Worksheets.Add(Employee.employee.Name);
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Role";
                worksheet.Cell(currentRow, 3).Value = "Monday";
                worksheet.Cell(currentRow, 4).Value = "Tuesday";
                worksheet.Cell(currentRow, 5).Value = "Wednesday ";
                worksheet.Cell(currentRow, 6).Value = "Thursday  ";
                worksheet.Cell(currentRow, 7).Value = "Friday  ";
                worksheet.Cell(currentRow, 8).Value = "Hours Worked";
                worksheet.Cell(currentRow, 9).Value = "Project";
                worksheet.Cell(currentRow, 10).Value = "Description";

                currentRow++;
                worksheet.Cell(currentRow, 1).Value = Employee.employee.Name;
                worksheet.Cell(currentRow, 2).Value = Employee.employee.role.RolesName;
                worksheet.Cell(currentRow, 3).Value = Employee.Mon;
                worksheet.Cell(currentRow, 4).Value = Employee.Tue;
                worksheet.Cell(currentRow, 5).Value = Employee.Wed;
                worksheet.Cell(currentRow, 6).Value = Employee.Thur;
                worksheet.Cell(currentRow, 7).Value = Employee.Fri;
                worksheet.Cell(currentRow, 8).Value = Employee.HoursWorked;
                worksheet.Cell(currentRow, 9).Value = Employee.project.ProjectName;
                if (Employee.project.ProjectName == null)
                {
                    worksheet.Cell(currentRow, 10).Value = "";
                }
                else
                {
                    worksheet.Cell(currentRow, 10).Value = Employee.Description;
                }
                    
              

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "users.xlsx");
                }
            }
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaiLam.Models;
using Microsoft.AspNetCore.Authorization;

namespace BaiLam.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly TimeSheetContext _context;

        public ProjectsController(TimeSheetContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectID,ProjectName,DateCreated,Deadline")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectID,ProjectName,DateCreated,Deadline")] Project project)
        {
            if (id != project.ProjectID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectID == id);
        }
    }
}

Views/ProjectDetails/Create.cshtml
@model BaiLam.Models.ProjectDetail

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-user mr-1"></i>
                        Assign employee
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"></div>
                            <div class="col-md-4">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="ProjectID" class="control-label"></label>
                                        <select asp-for="ProjectID" class="form-control" asp-items="ViewBag.ProjectID"></select>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="EmployeeID" class="control-label"></label>
                                        <select asp-for="EmployeeID" class="form-control" asp-items="ViewBag.EmployeeID"></select>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Description" class="control-label"></label>
                                        <input asp-for="Description" class="form-control" />
                                        <span asp-validation-for="Description" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Mon" class="control-label"></label>
                                        <input asp-for="Mon" class="price form-control" value="0" placeholder="Hours" />

                                        <span asp-validation-for="Mon" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Tue" class="control-label"></label>
                                        <input asp-for="Tue" class="price form-control" value="0" placeholder="Hours" />

                                        <span asp-validation-for="Tue" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Wed" class="control-label"></label>
                                        <input asp-for="Wed" class="price form-control" value="0" placeholder="Hours" />

                                        <span asp-validation-for="Wed" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Thur" class="control-label"></label>
                                        <input asp-for="Thur" class="price form-control" value="0" placeholder="Hours" />

                                        <span asp-validation-for="Thur" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Fri" class="control-label"></label>
                                        <input asp-for="Fri" class="price form-control" value="0" placeholder="Hours" />

                                        <span asp-validation-for="Fri" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="HoursWorked" class="control-label"></label>
                                        <input asp-for="HoursWorked" class="finaltotal form-control" value="0" placeholder="Hours" readonly />
                                        <span asp-validation-for="HoursWorked" class=" text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary" /> |
                                        <a class="btn btn-secondary" href="@ViewBag.returnUrl">Back to List</a>
                                    </div>
                                </form>
                            </div>
                            <div class="col">

                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
    <script>
        $('.price').on('keyup', function () {
            var val = +$(this).val();
            var finaltotal = 0;
            $('.price').each(function () {
                if (!isNaN($(this).val()))
                    finaltotal += Number($(this).val());
            });
            $('.finaltotal').val(finaltotal);
        });

        $(document).ready(function () {
            $('.price').trigger('keyup');
        });
    </script>
</body>

Views/ProjectDetails/Index.cshtml
@model IEnumerable<BaiLam.Models.ProjectDetail>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <div class="card mb-4">
                <div class="card-header">
                    <p>
                        <a class="btn btn-success" asp-action="Create" asp-route-id="@ViewBag.ProID">Assign employee</a>
                    </p>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.employee.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.employee.role)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Description)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Mon)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Tue)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Wed)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Thur)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Fri)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.HoursWorked)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.project)
                                    </th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.employee.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.employee.role.RolesName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Mon)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Tue)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Wed)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Thur)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Fri)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.HoursWorked)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.project.ProjectName)
                                        </td>

                                        <td>
                                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.detailID">Edit</a> |
                                            <a class="btn btn-info" asp-action="Details" asp-route-id="@item.detailID">Details</a> |
                                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.detailID">Delete</a> |
                                            <a class="btn btn-success" asp-action="Excel" asp-route-id="@item.detailID">Export</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <a class="btn btn-secondary" asp-controller="Projects" asp-action="Index">Back</a>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>