Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BaiLam.Models
{
    public class Project
    {
        public Project()
        {
            this.DateCreated = DateTime.Now;
            this.Deadline = DateTime.Now;
        }
        [Key]
        [Required]
        public int ProjectID { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        [Required]
        public string ProjectName { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Column(TypeName ="date")]
        public DateTime DateCreated { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Column(TypeName = "date")]
        public DateTime Deadline { get; set; }

        public virtual ICollection<ProjectDetail> projectdetail { get; set; }
        
    }
}

Controllers/ProjectDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaiLam.Models;
using Microsoft.AspNetCore.Authorization;
using ClosedXML.Excel;
using System.IO;

namespace BaiLam.Controllers
{
    [Authorize]
    public class ProjectDetailsController : Controller
    {
        private readonly TimeSheetContext _context;

        public ProjectDetailsController(TimeSheetContext context)
        {
            _context = context;
        }

        // GET: ProjectDetails
        public async Task<IActionResult> Index(int? id)
        {

            if (id == null) { return NotFound(); }
            ViewBag.ProID = id;
            var timeSheetContext = _context.ProjectDetails.Where(m => m.ProjectID == id).Include(p => p.employee).Include(p => p.project).Include(e => e.employee.role).Where(m => m.ProjectID == id);
            return View(await timeSheetContext.ToListAsync());
        }

        // GET: ProjectDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Url = _context.ProjectDetails.Where(p=>p.detailID==id).Include(m=>m.project).FirstOrDefault().ProjectID;
            var projectDetail = await _context.ProjectDetails
                .Include(p => p.employee)
                .Include(p => p.project)
                .FirstOrDefaultAsync(m => m.detailID == id);
            if (projectDetail == null)
            {
                return NotFound();
            }

            return View(projectDetail);
        }

        // GET: ProjectDetails/Create
        public IActionResult Create(int? id)
        {
            if (id == null) { return NotFound(); }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name");
            ViewData["ProjectID"] = new SelectList(_context.Projects.Where(p => p.ProjectID == id), "ProjectID", "ProjectName");
            return View();
        }

        // POST: ProjectDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("detailID,ProjectID,EmployeeID,Name,Description,Mon,Tue,Wed,Thur,Fri,HoursWorked")] ProjectDetail projectDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(projectDetail);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { id = projectDetail.ProjectID });
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // GET: ProjectDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectDetail = await _context.ProjectDetails.FindAsync(id);
            if (projectDetail == null)
            {
                return NotFound();
            }
            ViewBag.EmployeeName = _context.ProjectDetails.Where(p => p.detailID == id).Include(e=>e.employee).FirstOrDefault().employee.Name;
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // POST: ProjectDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("detailID,ProjectID,EmployeeID,Name,Description,Mon,Tue,Wed,Thur,Fri,HoursWorked")] ProjectDetail projectDetail)
        {
            if (id != projectDetail.detailID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(projectDetail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectDetailExists(projectDetail.detailID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index),new { id=projectDetail.ProjectID});
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();
            
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "EmployeeID", "Name", projectDetail.EmployeeID);
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ProjectID", "ProjectName", projectDetail.ProjectID);
            return View(projectDetail);
        }

        // GET: ProjectDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.returnUrl = Request.Headers["Referer"].ToString();

            var projectDetail = await _context.ProjectDetails
                .Include(p => p.employee)
                .Include(p => p.project)
                .FirstOrDefaultAsync(m => m.detailID == id);
            if (projectDetail == null)
            {
                return NotFound();
            }

            return View(projectDetail);
        }

        // POST: ProjectDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var projectDetail = await _context.ProjectDetails.FindAsync(id);
            _context.ProjectDetails.Remove(projectDetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = projectDetail.ProjectID });
        }

        private bool ProjectDetailExists(int id)
        {
            return _context.ProjectDetails.Any(e => e.detailID == id);
        }

        public IActionResult Excel(int? id)
        {
            if (id == null) { return NotFound(); }
            var Employee = _context.ProjectDetails.Where(p => p.detailID == id).Include(e=>e.employee).Include(r=>r.employee.role).Include(b=>b.project).FirstOrDefault();

            using (var workbook = new XLWorkbook())
            {

                var worksheet = workbook.Worksheets.Add(Employee.employee.Name);
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Role";
                worksheet.Cell(currentRow, 3).Value = "Monday";
                worksheet.Cell(currentRow, 4).Value = "Tuesday";
                worksheet.Cell(currentRow, 5).Value = "Wednesday ";
                worksheet.Cell(currentRow, 6).Value = "Thursday  ";
                worksheet.Cell(currentRow, 7).Value = "Friday  ";
                worksheet.Cell(currentRow, 8).Value = "Hours Worked";
                worksheet.Cell(currentRow, 9).Value = "Project";
                worksheet.Cell(currentRow, 10).Value = "Description";

                currentRow++;
                worksheet.Cell(currentRow, 1).Value = Employee.employee.Name;
                worksheet.Cell(currentRow, 2).Value = Employee.employee.role.RolesName;
                worksheet.Cell(currentRow, 3).Value = Employee.Mon;
                worksheet.Cell(currentRow, 4).Value = Employee.Tue;
                worksheet.Cell(currentRow, 5).Value = Employee.Wed;
                worksheet.Cell(currentRow, 6).Value = Employee.Thur;
                worksheet.Cell(currentRow, 7).Value = Employee.Fri;
                worksheet.Cell(currentRow, 8).Value = Employee.HoursWorked;
                worksheet.Cell(currentRow, 9).Value = Employee.project.ProjectName;
                if (Employee.project.ProjectName == null)
                {
                    worksheet.Cell(currentRow, 10).Value = "";
                }
                else
                {
                    worksheet.Cell(currentRow, 10).Value = Employee.Description;
                }
                    
              

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "users.xlsx");
                }
            }
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BaiLam.Models;
using Microsoft.AspNetCore.Authorization;

namespace BaiLam.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly TimeSheetContext _context;

        public ProjectsController(TimeSheetContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Projects.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectID,ProjectName,DateCreated,Deadline")] Project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProjectID,ProjectName,DateCreated,Deadline")] Project project)
        {
            if (id != project.ProjectID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .FirstOrDefaultAsync(m => m.ProjectID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ProjectID == id);
        }
    }
}

Views/Projects/Create.cshtml
@model BaiLam.Models.Project

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-user mr-1"></i>
                        Create new project
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col"></div>
                            <div class="col-md-4">
                                <form asp-action="Create">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="ProjectName" class="control-label"></label>
                                        <input asp-for="ProjectName" class="form-control" />
                                        <span asp-validation-for="ProjectName" class="text-danger"></span>
                                    </div>
                                    @*<div class="form-group">
                                    <label asp-for="DateCreated" class="control-label"></label>
                                    <input asp-for="DateCreated" class="form-control" />
                                    <span asp-validation-for="DateCreated" class="text-danger"></span>
                                </div>*@
                                    <div class="form-group">
                                        <label asp-for="Deadline" class="control-label"></label>
                                        <input asp-for="Deadline" class="form-control" />
                                        <span asp-validation-for="Deadline" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary" /> |
                                        <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                                    </div>
                                </form>
                            </div>
                            <div class="col"></div>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>

Views/Projects/Delete.cshtml
@model BaiLam.Models.Project

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-user mr-1"></i>
                        Delete Project: @Html.DisplayFor(Model => Model.ProjectName)
                    </div>
                    <div class="card-body">
                        <div class="col"></div>
                        <div class="col-md-4">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ProjectName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ProjectName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.DateCreated)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.DateCreated)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Deadline)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Deadline)
                                </dd>
                            </dl>

                            <form asp-action="Delete">
                                <input type="hidden" asp-for="ProjectID" />
                                <input type="submit" value="Delete" class="btn btn-danger" /> |
                                <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                            </form>
                        </div>
                        <div class="col"></div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>

Views/Projects/Details.cshtml
@model BaiLam.Models.Project

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <main>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-user mr-1"></i>
                        Details project: @Html.DisplayFor(Model => Model.ProjectName)
                    </div>
                    <div class="card-body">
                        <div class="col-md-6">
                            <dl class="row">
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.ProjectName)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.ProjectName)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.DateCreated)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.DateCreated)
                                </dd>
                                <dt class="col-sm-2">
                                    @Html.DisplayNameFor(model => model.Deadline)
                                </dt>
                                <dd class="col-sm-10">
                                    @Html.DisplayFor(model => model.Deadline)
                                </dd>
                            </dl>
                            <div>
                                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.ProjectID">Edit</a> |

                                <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>

Views/Projects/Edit.cshtml
@model BaiLam.Models.Project

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <div class="card-header">

                <h5>Edit project: @Html.DisplayFor(Model => Model.ProjectName)</h5>

            </div>
            <div class="card-body">
                <main>
                    <div class="row">
                        <div class="col"></div>
                        <div class="col-md-4">
                            <form asp-action="Edit">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="ProjectID" />
                                <div class="form-group">
                                    <label asp-for="ProjectName" class="control-label"></label>
                                    <input asp-for="ProjectName" class="form-control" />
                                    <span asp-validation-for="ProjectName" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="DateCreated" class="control-label"></label>
                                    <input asp-for="DateCreated" class="form-control" />
                                    <span asp-validation-for="DateCreated" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Deadline" class="control-label"></label>
                                    <input asp-for="Deadline" class="form-control" />
                                    <span asp-validation-for="Deadline" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Save" class="btn btn-primary" />
                                    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
                                </div>
                            </form>
                        </div>
                        <div class="col"></div>
                    </div>
                </main>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>

Views/Projects/Index.cshtml
@model IEnumerable<BaiLam.Models.Project>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<body class="sb-nav-fixed">
    <div id="layoutSidenav">
        <div id="layoutSidenav_content">
            <div class="card mb-4">
                <div class="card-header">
                    <p>
                        <a class="btn btn-success" asp-action="Create">Create New</a>
                    </p>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ProjectName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.DateCreated)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Deadline)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ProjectName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DateCreated)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Deadline)
                                        </td>
                                        <td>
                                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.ProjectID">Edit</a> |
                                            <a class="btn btn-info" asp-action="Details" asp-route-id="@item.ProjectID">Details</a> |
                                            <a class="btn btn-info" asp-controller="ProjectDetails" asp-action="Index" asp-route-id="@item.ProjectID">Employee</a> |
                                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.ProjectID">Delete</a>

                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Trần Tuấn Khải & Cao Minh Phát</div>
                        <div>
                            <a asp-action="Index">2020</a>
                            &middot;
                            <a asp-action="Index">2021</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
</body>